[package]
name = "nitrogql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql-parser = "0.4.0"
json-writer = "0.2.1"
lru = "0.9.0"