[workspace]
members = [
  "ast",
  "builtins",
  "cli",
  "checker",
  "config-file",
  "error",
  "graphql-printer",
  "json-printer",
  "parser",
  "printer",
  "semantics",
  "sourcemap-writer",
  "utils"
]