[package]
name = "nitrogql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json-writer = "0.2.1"
lru = "0.9.0"
glob = "0.3.1"
anyhow = "1.0.69"
pest = "2.5.5"
pest_derive = "2.5.5"
thiserror = "1.0.38"

[dev-dependencies]
insta = "1.28.0"