[package]
name = "nitrogql-config-file"
version = "0.1.0"
edition = "2021"

[features]
# Searches and loads config from file system.
fs = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9.19"
thiserror = "1.0.40"
