[package]
name = "nitrogql-json-printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json-writer = "0.2.1"
nitrogql-ast = { path = "../ast" }

[dev-dependencies]
insta = "1.28.0"
