[package]
name = "sourcemap-writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nitrogql-ast = { path = "../ast" }
nitrogql-utils = { path = "../utils" }
lru = "0.10.0"
json-writer = "0.2.1"
