name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: test
        run: cargo test
      # currently `cargo wasi test` doesn't run, so ensure at least that it builds
      - name: build (wasi)
        run: cargo run build --target wasm32-wasi
