name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      # - name: test (wasi)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --target wasm32-wasi
