name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: install additional targets
        run: rustup target add wasm32-wasi wasm32-unknown-unknown
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install wasm-opt
        run: npm install wasm-opt -g
      - name: build rust
        run: ./build/build-rust.sh
      - name: build node
        run: ./build/build-node.sh
      - name: publish to npm (cli)
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/cli/package.json"
          access: public
          greater-version-only: true
      - name: publish to npm (graphql-loader)
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/graphql-loader/package.json"
          access: public
          greater-version-only: true
      - name: publish to npm (rollup-plugin)
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/rollup-plugin/package.json"
          access: public
          greater-version-only: true
          